package io.github.droidkaigi.confsched.designsystem.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

private val fixedAccentColors = FixedAccentColors(
    primaryFixed = Color(0xFFD8E2FF),
    onPrimaryFixed = Color(0xFF001A43),
    onPrimaryFixedVariant = Color(0xFF2D4678),
    secondaryFixed = Color(0xFFE8DEFF),
    onSecondaryFixed = Color(0xFF1F1048),
    onSecondaryFixedVariant = Color(0xFF4B3E76),
    tertiaryFixed = Color(0xFFDBE1FF),
    onTertiaryFixed = Color(0xFF00174B),
    onTertiaryFixedVariant = Color(0xFF334478),
    primaryFixedDim = Color(0xFFAEC6FF),
    secondaryFixedDim = Color(0xFFCDBDFF),
    tertiaryFixedDim = Color(0xFFB4C5FF),
)

private val lightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
    primaryFixed = fixedAccentColors.primaryFixed,
    onPrimaryFixed = fixedAccentColors.onPrimaryFixed,
    onPrimaryFixedVariant = fixedAccentColors.onPrimaryFixedVariant,
    secondaryFixed = fixedAccentColors.secondaryFixed,
    onSecondaryFixed = fixedAccentColors.onSecondaryFixed,
    onSecondaryFixedVariant = fixedAccentColors.onSecondaryFixedVariant,
    tertiaryFixed = fixedAccentColors.tertiaryFixed,
    onTertiaryFixed = fixedAccentColors.onTertiaryFixed,
    onTertiaryFixedVariant = fixedAccentColors.onTertiaryFixedVariant,
    primaryFixedDim = fixedAccentColors.primaryFixedDim,
    secondaryFixedDim = fixedAccentColors.secondaryFixedDim,
    tertiaryFixedDim = fixedAccentColors.tertiaryFixedDim,
)

private val darkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
    primaryFixed = fixedAccentColors.primaryFixed,
    onPrimaryFixed = fixedAccentColors.onPrimaryFixed,
    onPrimaryFixedVariant = fixedAccentColors.onPrimaryFixedVariant,
    secondaryFixed = fixedAccentColors.secondaryFixed,
    onSecondaryFixed = fixedAccentColors.onSecondaryFixed,
    onSecondaryFixedVariant = fixedAccentColors.onSecondaryFixedVariant,
    tertiaryFixed = fixedAccentColors.tertiaryFixed,
    onTertiaryFixed = fixedAccentColors.onTertiaryFixed,
    onTertiaryFixedVariant = fixedAccentColors.onTertiaryFixedVariant,
    primaryFixedDim = fixedAccentColors.primaryFixedDim,
    secondaryFixedDim = fixedAccentColors.secondaryFixedDim,
    tertiaryFixedDim = fixedAccentColors.tertiaryFixedDim,
)

private val mediumContrastLightColorScheme = lightColorScheme(
    primary = primaryLightMediumContrast,
    onPrimary = onPrimaryLightMediumContrast,
    primaryContainer = primaryContainerLightMediumContrast,
    onPrimaryContainer = onPrimaryContainerLightMediumContrast,
    secondary = secondaryLightMediumContrast,
    onSecondary = onSecondaryLightMediumContrast,
    secondaryContainer = secondaryContainerLightMediumContrast,
    onSecondaryContainer = onSecondaryContainerLightMediumContrast,
    tertiary = tertiaryLightMediumContrast,
    onTertiary = onTertiaryLightMediumContrast,
    tertiaryContainer = tertiaryContainerLightMediumContrast,
    onTertiaryContainer = onTertiaryContainerLightMediumContrast,
    error = errorLightMediumContrast,
    onError = onErrorLightMediumContrast,
    errorContainer = errorContainerLightMediumContrast,
    onErrorContainer = onErrorContainerLightMediumContrast,
    background = backgroundLightMediumContrast,
    onBackground = onBackgroundLightMediumContrast,
    surface = surfaceLightMediumContrast,
    onSurface = onSurfaceLightMediumContrast,
    surfaceVariant = surfaceVariantLightMediumContrast,
    onSurfaceVariant = onSurfaceVariantLightMediumContrast,
    outline = outlineLightMediumContrast,
    outlineVariant = outlineVariantLightMediumContrast,
    scrim = scrimLightMediumContrast,
    inverseSurface = inverseSurfaceLightMediumContrast,
    inverseOnSurface = inverseOnSurfaceLightMediumContrast,
    inversePrimary = inversePrimaryLightMediumContrast,
    surfaceDim = surfaceDimLightMediumContrast,
    surfaceBright = surfaceBrightLightMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = surfaceContainerLowLightMediumContrast,
    surfaceContainer = surfaceContainerLightMediumContrast,
    surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
    primaryFixed = fixedAccentColors.primaryFixed,
    onPrimaryFixed = fixedAccentColors.onPrimaryFixed,
    onPrimaryFixedVariant = fixedAccentColors.onPrimaryFixedVariant,
    secondaryFixed = fixedAccentColors.secondaryFixed,
    onSecondaryFixed = fixedAccentColors.onSecondaryFixed,
    onSecondaryFixedVariant = fixedAccentColors.onSecondaryFixedVariant,
    tertiaryFixed = fixedAccentColors.tertiaryFixed,
    onTertiaryFixed = fixedAccentColors.onTertiaryFixed,
    onTertiaryFixedVariant = fixedAccentColors.onTertiaryFixedVariant,
    primaryFixedDim = fixedAccentColors.primaryFixedDim,
    secondaryFixedDim = fixedAccentColors.secondaryFixedDim,
    tertiaryFixedDim = fixedAccentColors.tertiaryFixedDim,
)

private val highContrastLightColorScheme = lightColorScheme(
    primary = primaryLightHighContrast,
    onPrimary = onPrimaryLightHighContrast,
    primaryContainer = primaryContainerLightHighContrast,
    onPrimaryContainer = onPrimaryContainerLightHighContrast,
    secondary = secondaryLightHighContrast,
    onSecondary = onSecondaryLightHighContrast,
    secondaryContainer = secondaryContainerLightHighContrast,
    onSecondaryContainer = onSecondaryContainerLightHighContrast,
    tertiary = tertiaryLightHighContrast,
    onTertiary = onTertiaryLightHighContrast,
    tertiaryContainer = tertiaryContainerLightHighContrast,
    onTertiaryContainer = onTertiaryContainerLightHighContrast,
    error = errorLightHighContrast,
    onError = onErrorLightHighContrast,
    errorContainer = errorContainerLightHighContrast,
    onErrorContainer = onErrorContainerLightHighContrast,
    background = backgroundLightHighContrast,
    onBackground = onBackgroundLightHighContrast,
    surface = surfaceLightHighContrast,
    onSurface = onSurfaceLightHighContrast,
    surfaceVariant = surfaceVariantLightHighContrast,
    onSurfaceVariant = onSurfaceVariantLightHighContrast,
    outline = outlineLightHighContrast,
    outlineVariant = outlineVariantLightHighContrast,
    scrim = scrimLightHighContrast,
    inverseSurface = inverseSurfaceLightHighContrast,
    inverseOnSurface = inverseOnSurfaceLightHighContrast,
    inversePrimary = inversePrimaryLightHighContrast,
    surfaceDim = surfaceDimLightHighContrast,
    surfaceBright = surfaceBrightLightHighContrast,
    surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = surfaceContainerLowLightHighContrast,
    surfaceContainer = surfaceContainerLightHighContrast,
    surfaceContainerHigh = surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
    primaryFixed = fixedAccentColors.primaryFixed,
    onPrimaryFixed = fixedAccentColors.onPrimaryFixed,
    onPrimaryFixedVariant = fixedAccentColors.onPrimaryFixedVariant,
    secondaryFixed = fixedAccentColors.secondaryFixed,
    onSecondaryFixed = fixedAccentColors.onSecondaryFixed,
    onSecondaryFixedVariant = fixedAccentColors.onSecondaryFixedVariant,
    tertiaryFixed = fixedAccentColors.tertiaryFixed,
    onTertiaryFixed = fixedAccentColors.onTertiaryFixed,
    onTertiaryFixedVariant = fixedAccentColors.onTertiaryFixedVariant,
    primaryFixedDim = fixedAccentColors.primaryFixedDim,
    secondaryFixedDim = fixedAccentColors.secondaryFixedDim,
    tertiaryFixedDim = fixedAccentColors.tertiaryFixedDim,
)

private val mediumContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkMediumContrast,
    onPrimary = onPrimaryDarkMediumContrast,
    primaryContainer = primaryContainerDarkMediumContrast,
    onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
    secondary = secondaryDarkMediumContrast,
    onSecondary = onSecondaryDarkMediumContrast,
    secondaryContainer = secondaryContainerDarkMediumContrast,
    onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
    tertiary = tertiaryDarkMediumContrast,
    onTertiary = onTertiaryDarkMediumContrast,
    tertiaryContainer = tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
    error = errorDarkMediumContrast,
    onError = onErrorDarkMediumContrast,
    errorContainer = errorContainerDarkMediumContrast,
    onErrorContainer = onErrorContainerDarkMediumContrast,
    background = backgroundDarkMediumContrast,
    onBackground = onBackgroundDarkMediumContrast,
    surface = surfaceDarkMediumContrast,
    onSurface = onSurfaceDarkMediumContrast,
    surfaceVariant = surfaceVariantDarkMediumContrast,
    onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
    outline = outlineDarkMediumContrast,
    outlineVariant = outlineVariantDarkMediumContrast,
    scrim = scrimDarkMediumContrast,
    inverseSurface = inverseSurfaceDarkMediumContrast,
    inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
    inversePrimary = inversePrimaryDarkMediumContrast,
    surfaceDim = surfaceDimDarkMediumContrast,
    surfaceBright = surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
    surfaceContainer = surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
    primaryFixed = fixedAccentColors.primaryFixed,
    onPrimaryFixed = fixedAccentColors.onPrimaryFixed,
    onPrimaryFixedVariant = fixedAccentColors.onPrimaryFixedVariant,
    secondaryFixed = fixedAccentColors.secondaryFixed,
    onSecondaryFixed = fixedAccentColors.onSecondaryFixed,
    onSecondaryFixedVariant = fixedAccentColors.onSecondaryFixedVariant,
    tertiaryFixed = fixedAccentColors.tertiaryFixed,
    onTertiaryFixed = fixedAccentColors.onTertiaryFixed,
    onTertiaryFixedVariant = fixedAccentColors.onTertiaryFixedVariant,
    primaryFixedDim = fixedAccentColors.primaryFixedDim,
    secondaryFixedDim = fixedAccentColors.secondaryFixedDim,
    tertiaryFixedDim = fixedAccentColors.tertiaryFixedDim,
)

private val highContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkHighContrast,
    onPrimary = onPrimaryDarkHighContrast,
    primaryContainer = primaryContainerDarkHighContrast,
    onPrimaryContainer = onPrimaryContainerDarkHighContrast,
    secondary = secondaryDarkHighContrast,
    onSecondary = onSecondaryDarkHighContrast,
    secondaryContainer = secondaryContainerDarkHighContrast,
    onSecondaryContainer = onSecondaryContainerDarkHighContrast,
    tertiary = tertiaryDarkHighContrast,
    onTertiary = onTertiaryDarkHighContrast,
    tertiaryContainer = tertiaryContainerDarkHighContrast,
    onTertiaryContainer = onTertiaryContainerDarkHighContrast,
    error = errorDarkHighContrast,
    onError = onErrorDarkHighContrast,
    errorContainer = errorContainerDarkHighContrast,
    onErrorContainer = onErrorContainerDarkHighContrast,
    background = backgroundDarkHighContrast,
    onBackground = onBackgroundDarkHighContrast,
    surface = surfaceDarkHighContrast,
    onSurface = onSurfaceDarkHighContrast,
    surfaceVariant = surfaceVariantDarkHighContrast,
    onSurfaceVariant = onSurfaceVariantDarkHighContrast,
    outline = outlineDarkHighContrast,
    outlineVariant = outlineVariantDarkHighContrast,
    scrim = scrimDarkHighContrast,
    inverseSurface = inverseSurfaceDarkHighContrast,
    inverseOnSurface = inverseOnSurfaceDarkHighContrast,
    inversePrimary = inversePrimaryDarkHighContrast,
    surfaceDim = surfaceDimDarkHighContrast,
    surfaceBright = surfaceBrightDarkHighContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = surfaceContainerLowDarkHighContrast,
    surfaceContainer = surfaceContainerDarkHighContrast,
    surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
    primaryFixed = fixedAccentColors.primaryFixed,
    onPrimaryFixed = fixedAccentColors.onPrimaryFixed,
    onPrimaryFixedVariant = fixedAccentColors.onPrimaryFixedVariant,
    secondaryFixed = fixedAccentColors.secondaryFixed,
    onSecondaryFixed = fixedAccentColors.onSecondaryFixed,
    onSecondaryFixedVariant = fixedAccentColors.onSecondaryFixedVariant,
    tertiaryFixed = fixedAccentColors.tertiaryFixed,
    onTertiaryFixed = fixedAccentColors.onTertiaryFixed,
    onTertiaryFixedVariant = fixedAccentColors.onTertiaryFixedVariant,
    primaryFixedDim = fixedAccentColors.primaryFixedDim,
    secondaryFixedDim = fixedAccentColors.secondaryFixedDim,
    tertiaryFixedDim = fixedAccentColors.tertiaryFixedDim,
)

data class FixedAccentColors(
    val primaryFixed: Color,
    val onPrimaryFixed: Color,
    val onPrimaryFixedVariant: Color,
    val secondaryFixed: Color,
    val onSecondaryFixed: Color,
    val onSecondaryFixedVariant: Color,
    val tertiaryFixed: Color,
    val onTertiaryFixed: Color,
    val onTertiaryFixedVariant: Color,
    val primaryFixedDim: Color,
    val secondaryFixedDim: Color,
    val tertiaryFixedDim: Color,
)

@Composable
fun KaigiTheme(
    colorContrast: ColorContrast = ColorContrast.Default,
    darkTheme: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit,
) {
    val colorScheme = when {
        darkTheme && colorContrast == ColorContrast.Default -> darkScheme
        darkTheme && colorContrast == ColorContrast.Medium -> mediumContrastDarkColorScheme
        darkTheme && colorContrast == ColorContrast.High -> highContrastDarkColorScheme
        !darkTheme && colorContrast == ColorContrast.Default -> lightScheme
        !darkTheme && colorContrast == ColorContrast.Medium -> mediumContrastLightColorScheme
        !darkTheme && colorContrast == ColorContrast.High -> highContrastLightColorScheme
        else -> darkScheme
    }

    MaterialTheme(
        colorScheme = colorScheme,
        content = content,
    )
}

enum class ColorContrast {
    Default,
    Medium,
    High,
}
